# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim, um objeto composto multidimensional, como uma matriz, pode receber um objeto composto unidimensional, como um vetor, desde que haja compatibilidade entre suas dimensões. Isso ocorre porque o vetor pode ser inserido em uma das dimensões da matriz, como em uma linha ou coluna, desde que o número de elementos seja correspondente. Caso as dimensões não sejam compatíveis, a atribuição não será possível.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [2]:
#Instanciando os objetos dos exercícios anteriores
lista_genes = ["BRCA1", "CDKN2A", "TP53", "KRAS", "SMAD4"]
dicionario_genes={lista_genes[0]: len(lista_genes[0]),
                    lista_genes[1]: len(lista_genes[1]),
                    lista_genes[2]: len(lista_genes[2]),
                    lista_genes[3]: len(lista_genes[3]),
                    lista_genes[4]: len(lista_genes[4])}
listaBRCA1 = [lista_genes[0], len(lista_genes[0]), lista_genes[0][:2], lista_genes[0].count("A"), "hu" in lista_genes[0]]
listaCDKN2A = [lista_genes[1], len(lista_genes[1]), lista_genes[1][:2], lista_genes[1].count("A"), "hu" in lista_genes[1]]
listaTP53 = [lista_genes[2], len(lista_genes[2]), lista_genes[2][:2], lista_genes[2].count("A"), "hu" in lista_genes[2]]
listaKRAS = [lista_genes[3], len(lista_genes[3]), lista_genes[3][:2], lista_genes[3].count("A"), "hu" in lista_genes[3]]
listaSMAD4 = [lista_genes[4], len(lista_genes[4]), lista_genes[4][:2], lista_genes[4].count("A"), "hu" in lista_genes[4]]

In [3]:
matriz_genes = [listaBRCA1, listaCDKN2A, listaTP53, listaKRAS, listaSMAD4]
matriz_genes

[['BRCA1', 5, 'BR', 1, False],
 ['CDKN2A', 6, 'CD', 1, False],
 ['TP53', 4, 'TP', 0, False],
 ['KRAS', 4, 'KR', 1, False],
 ['SMAD4', 5, 'SM', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [4]:
#Chamando numpy para criar um array
import numpy as np

array_genes = np.array(matriz_genes)
array_genes

array([['BRCA1', '5', 'BR', '1', 'False'],
       ['CDKN2A', '6', 'CD', '1', 'False'],
       ['TP53', '4', 'TP', '0', 'False'],
       ['KRAS', '4', 'KR', '1', 'False'],
       ['SMAD4', '5', 'SM', '1', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [5]:
array_genes[2, :5]

array(['TP53', '4', 'TP', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [6]:
"HU" in array_genes[0:5, 0]

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [7]:
array_genes[1][0][:2], array_genes[3][0][:2]

('CD', 'KR')

In [8]:
np.char.count(array_genes[[1, 3], 0], "A")

array([1, 1])

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [9]:
dicionario10 = {lista_genes[0]: listaBRCA1, lista_genes[1]: listaCDKN2A, lista_genes[2]: listaTP53, lista_genes[3]: listaKRAS, lista_genes[4]: listaSMAD4}
import pandas as pd
dataframe_genes = pd.DataFrame(dicionario10,    index = ["Nome do gene", "Tamanho do gene", "Início do nome do gene", "Número de A's no nome do gene", "HU no nome do gene"])
dataframe_genes

                               BRCA1  CDKN2A   TP53   KRAS  SMAD4
Nome do gene                   BRCA1  CDKN2A   TP53   KRAS  SMAD4
Tamanho do gene                    5       6      4      4      5
Início do nome do gene            BR      CD     TP     KR     SM
Número de A's no nome do gene      1       1      0      1      1
HU no nome do gene             False   False  False  False  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [10]:
dataframe_genes.loc[["Tamanho do gene", "Número de A's no nome do gene"]]

                              BRCA1 CDKN2A TP53 KRAS SMAD4
Tamanho do gene                   5      6    4    4     5
Número de A's no nome do gene     1      1    0    1     1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [11]:
dataframe_genes.loc["HU no nome do gene", ["BRCA1", "TP53"]]

BRCA1    False
TP53     False
Name: HU no nome do gene, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [14]:
df = pd.read_csv("data.csv")
resultado = {
    "num_entradas": len(df),
    "classes_colunas": df.dtypes.tolist(),
    "num_elementos": df.count().tolist(),
    "col1": [df.iloc[:,0].mean(), df.iloc[:,0].std(), df.iloc[:,0].quantile(0.75)],
    "col4": [df.iloc[:,3].mean(), df.iloc[:,3].std(), df.iloc[:,3].quantile(0.75)],
    "col9": [df.iloc[:,8].mean(), df.iloc[:,8].std(), df.iloc[:,8].quantile(0.75)]
}
resultado

{'num_entradas': 36634,
 'classes_colunas': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'num_elementos': [36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634,
  36634],
 'col1': [np.float64(548661.9371894961),
  np.float64(259912.9264939009),
  np.float64(774252.0)],
 'col4': [np.float64(731478.0068460993),
  np.float64(17523003.588415086),
  np.float64(0.0)],
 'col9': [np.float64(2571004.0973420865),
  np.float64(20367766.569178067),
  np.float64(1128871.1824999999)]}